# Generated by Django 5.2.11 on 2026-02-15 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('person_type', models.CharField(choices=[('Natural', 'Natural'), ('Empresa', 'Empresa')], default='natural', max_length=20, verbose_name='Tipo de Cliente')),
                ('document_type', models.CharField(blank=True, choices=[('Dni', 'Dni'), ('Carnet extranjeria', 'Carnet extranjeria'), ('Pasaporte', 'Pasaporte'), ('', '')], default=None, max_length=30, null=True, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, verbose_name='Télefono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('name', models.CharField(max_length=255, verbose_name='Empresa')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='RUC')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
