# Generated by Django 5.2.11 on 2026-02-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.CharField(blank=True, choices=[('Administrativos', 'Administrativos'), ('Agricultor', 'Agricultor'), ('Albañil', 'Albañil'), ('Almacenero', 'Almacenero'), ('Carpintero', 'Carpintero'), ('Chofer', 'Chofer'), ('Comerciante', 'Comerciante'), ('Electricista', 'Electricista'), ('Estudiante', 'Estudiante'), ('Gasfitero', 'Gasfitero'), ('Ingeniero', 'Ingeniero'), ('Maestro de obra', 'Maestro de obra'), ('Operario', 'Operario'), ('Pesonal de limpieza', 'Personal de limpieza'), ('Personal de seguridad', 'Personal de seguridad'), ('Pescador artesanal', 'Personal artesanal'), ('Pintor', 'Pintor'), ('Soldador', 'Soldador'), ('Otros', 'Otros')], max_length=255, null=True, verbose_name='Oficio / Profesión'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('Agroindustrial', 'Agroindustrial'), ('Alimentos y bebidas', 'Alimentos y bebidas'), ('Construccion', 'Construccion'), ('Contratistas', 'Contratistas'), ('Distribuidrores', 'Distribuidrores'), ('Empresas de limpieza industrial', 'Empresas de limpieza industrial'), ('Energía', 'Energía'), ('Forestal / madereras', 'Forestal / madereras'), ('Frigoríficos', 'Frigoríficos'), ('Imprentas industriales', 'Ii'), ('Laboratorios', 'La'), ('Logística y almacenes', 'Logística y almacenes'), ('Mantenimiento industrial', 'Mantenimiento industrial'), ('Manufactura', 'Manufactura'), ('Metalurgía', 'Metalurgía'), ('Minería', 'Minería'), ('Sector Público', 'Sector Público'), ('Oil & Gas', 'Oil & Gas'), ('Pesca industrial', 'Pesca industrial'), ('Plantas de tratamiento de aguas residuales', 'Plantas de tratamiento de aguas residuales'), ('Químico', 'Químico'), ('Retail', 'Retail'), ('Saneamiento / gestión de residuos / plantas de reciclaje', 'Saneamiento / gestión de residuos / plantas de reciclaje'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Textil', 'Textil'), ('Transporte', 'Transporte'), ('Otros', 'Ot')], max_length=255, null=True, verbose_name='Rubro'),
        ),
    ]
