# Generated by Django 5.2.11 on 2026-02-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo'),
        ),
    ]
