# Generated by Django 5.2.11 on 2026-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_job_alter_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('Agroindustrial', 'Agroindustrial'), ('Alimentos y bebidas', 'Alimentos y bebidas'), ('Construccion', 'Construccion'), ('Contratistas', 'Contratistas'), ('Distribuidrores', 'Distribuidrores'), ('Empresas de limpieza industrial', 'Empresas de limpieza industrial'), ('Energía', 'Energía'), ('Forestal / madereras', 'Forestal / madereras'), ('Frigoríficos', 'Frigoríficos'), ('Imprentas industriales', 'Imprentas industriales'), ('Laboratorios', 'Laboratorios'), ('Logística y almacenes', 'Logística y almacenes'), ('Mantenimiento industrial', 'Mantenimiento industrial'), ('Manufactura', 'Manufactura'), ('Metalurgía', 'Metalurgía'), ('Minería', 'Minería'), ('Sector Público', 'Sector Público'), ('Oil & Gas', 'Oil & Gas'), ('Pesca industrial', 'Pesca industrial'), ('Plantas de tratamiento de aguas residuales', 'Plantas de tratamiento de aguas residuales'), ('Químico', 'Químico'), ('Retail', 'Retail'), ('Saneamiento / gestión de residuos / plantas de reciclaje', 'Saneamiento / gestión de residuos / plantas de reciclaje'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Textil', 'Textil'), ('Transporte', 'Transporte'), ('Otros', 'Otros')], max_length=255, null=True, verbose_name='Rubro'),
        ),
    ]
