# Generated by Django 5.2.11 on 2026-02-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_full_name_remove_client_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
    ]
