# Generated by Django 5.2.11 on 2026-02-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Categoría')),
                ('detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalles complementarios')),
            ],
            options={
                'verbose_name': 'Categoria de Usuario',
                'verbose_name_plural': 'Categorias de Usuario',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='usercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usercategory', verbose_name='Categoría de Usuario'),
        ),
    ]
