# Generated by Django 5.2.11 on 2026-02-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('created_at',), 'verbose_name': 'Canal', 'verbose_name_plural': 'Canales'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
