# Generated by Django 5.2.11 on 2026-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_channel_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='type',
            field=models.CharField(blank=True, choices=[('Redes Sociales', 'Redes Sociales'), ('Feria', 'Feria')], max_length=50, null=True, verbose_name='Tipo de Canal'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, help_text='Ingrese el nombre del evento o feria', max_length=500, null=True, verbose_name='Detalle de Canal'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Canal'),
        ),
    ]
