# Generated by Django 5.2.11 on 2026-02-11 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_channel_type_alter_channel_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalles complementarios'),
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Linea')),
                ('detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalles complementarios')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Línea de Producto',
                'verbose_name_plural': 'Líneas de Productos',
                'ordering': ('created_at',),
            },
        ),
    ]
