# Generated by Django 5.2.11 on 2026-02-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_product_detail_productline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productline_product', to='maintenance.productline', verbose_name='Línea de Producto'),
        ),
    ]
