# Generated by Django 5.2.11 on 2026-02-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_remove_channel_type_channel_fair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='fair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='maintenance.fair', verbose_name='Feria Asociada'),
        ),
    ]
