# Generated by Django 5.2.11 on 2026-02-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_channel_fair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='fair',
        ),
    ]
