# Generated by Django 5.2.11 on 2026-02-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_remove_channel_fair'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('Físico', 'Físico'), ('Digital', 'Digital')], max_length=255, null=True, verbose_name='Tipo de Canal'),
        ),
    ]
