# Generated by Django 5.2.11 on 2026-02-15 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('En contacto', 'En contacto'), ('Cotizado', 'Cotizado'), ('Vendido', 'Vendido'), ('Perdido', 'Perdido')], max_length=50, verbose_name='Estado')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto')),
                ('reason', models.CharField(blank=True, choices=[('Competencia', 'Competencia'), ('Falta de Stock', 'Falta de Stock'), ('Despacho fuera de tiempo', 'Despacho fuera de tiempo'), ('Precio de Producto', 'Precio de Producto')], max_length=100, null=True, verbose_name='Razón')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Fecha de inicio de contacto', verbose_name='Fecha de contacto')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('created_at',),
            },
        ),
    ]
