# Generated by Django 5.2.11 on 2026-02-09 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('En contacto', 'En contacto'), ('Cotizado', 'Cotizado'), ('Vendido', 'Vendido'), ('Perdido', 'Perdido')], max_length=50, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón')),
                ('date', models.DateField(help_text='Fecha de fallecimiento de difunto', verbose_name='Fecha de nacimiento')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_lead', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_lead', to='maintenance.channel')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_lead', to='maintenance.product')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
