# Generated by Django 5.2.11 on 2026-02-16 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('state', models.BooleanField(default=True, verbose_name='Activo?')),
                ('status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('En contacto', 'En contacto'), ('Cotizado', 'Cotizado'), ('Vendido', 'Vendido'), ('Perdido', 'Perdido')], max_length=50, verbose_name='Estado')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto')),
                ('reason', models.CharField(blank=True, choices=[('Competencia', 'Competencia'), ('Falta de Stock', 'Falta de Stock'), ('Despacho fuera de tiempo', 'Despacho fuera de tiempo'), ('Precio de Producto', 'Precio de Producto')], max_length=100, null=True, verbose_name='Razón')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Fecha de inicio de contacto', verbose_name='Fecha de contacto')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_lead', to=settings.AUTH_USER_MODEL, verbose_name='Asesor')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_lead', to='maintenance.channel', verbose_name='Canal')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_lead', to='client.client', verbose_name='Cliente')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('fair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fair_lead', to='maintenance.fair', verbose_name='Feria')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_lead', to='maintenance.product', verbose_name='Producto')),
                ('product_lines', models.ManyToManyField(blank=True, related_name='leads', to='maintenance.productline', verbose_name='Líneas de Producto de Interés')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('created_at',),
            },
        ),
    ]
