# Generated by Django 5.2.11 on 2026-02-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('En contacto', 'En contacto'), ('Cotizado', 'Cotizado'), ('Vendido', 'Vendido'), ('Perdido', 'Perdido')], default='Nuevo', max_length=50, verbose_name='Estado'),
        ),
    ]
