# Generated by Django 5.2.11 on 2026-02-15 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('crm', '0001_initial'),
        ('maintenance', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_lead', to=settings.AUTH_USER_MODEL, verbose_name='Asesor'),
        ),
        migrations.AddField(
            model_name='lead',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_lead', to='maintenance.channel', verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_lead', to='client.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fair_lead', to='maintenance.fair', verbose_name='Feria'),
        ),
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_lead', to='maintenance.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_lines',
            field=models.ManyToManyField(blank=True, related_name='leads', to='maintenance.productline', verbose_name='Líneas de Producto de Interés'),
        ),
    ]
