# Generated by Django 5.2.11 on 2026-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_status'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='product_lines',
            field=models.ManyToManyField(related_name='leads', to='maintenance.productline', verbose_name='Líneas de Producto de Interés'),
        ),
    ]
