# Generated by Django 5.2.11 on 2026-02-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_document_number_alter_client_full_name'),
        ('crm', '0002_lead_client'),
        ('maintenance', '0002_alter_channel_options_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('created_at',), 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_lead', to=settings.AUTH_USER_MODEL, verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_lead', to='client.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateField(help_text='Fecha de inicio de contacto', verbose_name='Fecha de contacto'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_lead', to='maintenance.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reason',
            field=models.CharField(blank=True, choices=[('Competencia', 'Competencia'), ('Falta de Stock', 'Falta de Stock'), ('Despacho fuera de tiempo', 'Despacho fuera de tiempo'), ('Precio de Producto', 'Precio de Producto')], max_length=100, null=True, verbose_name='Razón'),
        ),
    ]
