# Generated by Django 5.2.11 on 2026-02-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_options_alter_lead_agent_and_more'),
        ('maintenance', '0003_channel_type_alter_channel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_lead', to='maintenance.channel', verbose_name='Canal'),
        ),
    ]
