# Generated by Django 5.2.11 on 2026-02-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_lead_channel'),
        ('maintenance', '0009_remove_channel_fair'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fair_lead', to='maintenance.fair'),
        ),
    ]
