# Generated by Django 5.2.11 on 2026-02-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_fair'),
        ('maintenance', '0010_channel_channel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fair_lead', to='maintenance.productline', verbose_name='Línea de Producto de Interés'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fair_lead', to='maintenance.fair', verbose_name='Feria'),
        ),
    ]
