# Generated by Django 5.2.11 on 2026-02-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_lead_product_line_alter_lead_fair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto'),
        ),
    ]
